{% set name = "xarray-ceos-alos2" %}
{% set version = "2024.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d1697147d654e1e9f19534d264f9812dbb147e53b0acdccb56e0c115d350c483

build:
  noarch: python
  entry_points:
    - ceos-alos2-create-cache = ceos_alos2.sar_image.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - cytoolz
    - python-dateutil
    - xarray
    - xarray-datatree
    - numpy
    - construct >=2.10
    - fsspec
    - platformdirs
    - exceptiongroup

test:
  imports:
    - ceos_alos2
  commands:
    - pip check
    - ceos-alos2-create-cache --help
  requires:
    - pip

about:
  home: https://github.com/umr-lops/xarray-ceos-alos2
  summary: xarray reader for advanced land observing satellite 2 (ALOS2) CEOS files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keewis
    - agrouaze
